version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: curconv-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: convert
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U user -d convert'" ]
      timeout: 5s
      retries: 4
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curconv-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: convert
      API_KEY: putyourkeyhere
      FOREX_API: https://api.fastforex.io
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
